---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Validation Conformance Pack - DO NOT DELETE'

Parameters:

  ResourceBucket:
    Description: S3 Bucket where resources are stored.
    Type: String
    Default: 'solutions.rwick.it'

  ProjectName:
    Description: Name of project prefix in bucket
    Type: String
    Default: 'config-conformance-packs'

  DeploymentOUs:
    Description: Which ORG OU(s) is this deploying to
    Type: String
    MinLength: 1

  Regions:
    Description: Which regions is this deploying to
    Type: String
    MinLength: 1

  Nonce:
    Type: String
    Description: Random value used to generate new version of lambda function

Resources:

  ConformancePackStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: !Ref ProjectName
      Description: Validation Conformance Pack - DO NOT DELETE
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      StackInstancesGroup:
        - Regions:
            !Split [ "," , !Ref Regions ]
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOUs
      TemplateURL: !Sub https://${ResourceBucket}.s3.amazonaws.com/${ProjectName}/cloudformation/${ProjectName}.yml
      Parameters:
        - ParameterKey: AccountType
          ParameterValue: workload
        - ParameterKey: Nonce
          ParameterValue: !Ref Nonce